name: Flutter APK Build

on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.5'  # replace with your Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Generate localization
        run: flutter gen-l10n

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/app/outputs/flutter-apk/app-release.apk